version: '3'

services:
  bot:
    build: .
    image: wiibleyde/chat:latest
    container_name: chat
    restart: always
    depends_on:
      - mongo
    ports:
      - 13337:13337
    volumes:
      - ./logs/:/app/logs/
    environment:
      - CHAT_PORT=13336
      - MAX_USERS=100

  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - 6379:6379